#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/servlet?characterEncoding=UTF-8&useUnicode=true&useSSL=false
#    username: root
#    password: shenxb
#    type: com.alibaba.druid.pool.DruidDataSource
#mybatis:
#  type-aliases-package: com.gaodun.bootshiro.entity
#  mapper-locations: classpath*:mapper/*.xml
#logging:
#  level:
#    com.com.gaodun.bootshiro.mapper: debug